CREATE TABLE coach_client (
    id SERIAL PRIMARY KEY,
    coach_id BIGINT UNIQUE NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    client_id BIGINT UNIQUE NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    started_at TIMESTAMP WITH TIME ZONE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);