CREATE TABLE goal (
    id BIGSERIAL PRIMARY KEY,
    cycle_id BIGINT NOT NULL,
    achieved BOOLEAN NOT NULL DEFAULT FALSE,
    text VARCHAR(1000) NOT NULL,
    CONSTRAINT fk_cycle FOREIGN KEY(cycle_id) REFERENCES cycle(id) ON DELETE CASCADE
);
