name: CD - Deploy to Render

on:
  workflow_run:
    workflows: ["CI - Build and Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Decode JWT keystore from secret
        run: |
          echo "${{ secrets.JWT_KEYSTORE_B64 }}" | base64 -d > src/main/resources/keystore.p12

      - name: Build Docker image
        run: docker build -t my-fitness-app .

      - name: Deploy to Render via deploy hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
